/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 crt.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/crt.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.TVfront} position={[11.057, -26.295, -18.646]} rotation={[-Math.PI, 0, -Math.PI]} />
            <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.TVfront} position={[0, -26.836, 0]} />
            <mesh geometry={nodes.defaultMaterial007.geometry} material={materials.TVfront} position={[26.908, -17.616, -17.225]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.173, 0.159, 0.173]} />
            <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.TVfront} />
            <mesh geometry={nodes.defaultMaterial008.geometry} material={materials.TVfront} position={[0.003, -19.835, 0.852]} scale={0.11} />
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.TVback} position={[0, -0.042, 0]} scale={[0.99, 0.99, 1]} />
            {/* <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.TVScreen} position={[0, 0, -166.617]} scale={398.216} /> */}
            <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.TVfront} position={[3.169, -20.046, -18.301]} rotation={[0, 0, -0.596]} scale={[0.378, 0.378, 0.221]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/crt.glb')
